resources:

- name: my-repo
  type: git
  source:
    uri: https://github.com/maliksalman/pcf-boot-samples.git
    branch: concourse

jobs:

- name: build
  plan:

  - get: my-repo
    trigger: true

  - task: go-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
          tag: 1.188.0
      inputs:
      - name: my-repo
      run:
        path: sh
        args:
        - -exc
        - |
          apt-get install -y golang
          go build my-repo/go/hello.go
          ./hello &
          curl -v localhost:8080
