resources:

- name: my-repo
  type: git
  source:
    uri: https://github.com/maliksalman/concourse-samples.git
    branch: concourse

- name: pcfdev
  type: cf
  source:
    api: ((CF_API_URL))
    username: ((CF_USER))
    password: ((CF_PASSWORD))
    organization: ((CF_ORG))
    space: ((CF_SPACE))
    skip_cert_check: true

jobs:

- name: build-test-deploy
  plan:

  - get: my-repo
    trigger: true

  - task: go-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
          tag: 1.188.0
      inputs:
      - name: my-repo
      outputs:
      - name: go-bin
      run:
        path: sh
        args:
        - -exc
        - |
          apt-get install -y golang
          go build my-repo/go/hello.go
          cp hello go-bin/hello-go
          cp my-repo/go/manifest.yml go-bin/

  - task: go-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
          tag: 1.188.0
      inputs:
      - name: go-bin
      run:
        path: sh
        args:
        - -exc
        - |
          go-bin/hello-go &
          sleep 1
          curl -v http://127.0.0.1:8080/


  - put: pcfdev
    params:
      manifest: go-bin/manifest.yml
      path: go-bin/
