resources:

- name: my-repo
  type: git
  source:
    uri: https://github.com/maliksalman/concourse-samples.git
    branch: concourse

- name: version
  type: semver
  source:
    driver: s3
    bucket: ((S3_BUCKET))
    key: current-version
    disable_ssl: true
    endpoint: ((S3_ENDPOINT))
    access_key_id: ((S3_ACCESS_KEY))
    secret_access_key: ((S3_SECRET_KEY))
    initial_version: 1.0.0

- name: hello-artifacts
  type: s3
  source:
    bucket: ((S3_BUCKET))
    regexp: hello-go-(.*).zip
    disable_ssl: true
    endpoint: ((S3_ENDPOINT))
    access_key_id: ((S3_ACCESS_KEY))
    secret_access_key: ((S3_SECRET_KEY))

- name: pcfdev
  type: cf
  source:
    api: ((CF_API_URL))
    username: ((CF_USER))
    password:  ((CF_PASSWORD))
    organization:  ((CF_ORG))
    space:  ((CF_SPACE))
    skip_cert_check: true

jobs:

- name: package
  plan:
  - get: my-repo
    trigger: true
  - put: version
    params:
      bump: patch
  - task: build
    file: my-repo/ci/tasks-s3/package.yml
  - put: hello-artifacts
    params:
      file: go-bin/hello-go-*.zip

- name: deploy
  plan:
  - get: hello-artifacts
    trigger: true
    passed: [package]
  - get: my-repo
  - task: copy-artifacts
    file: my-repo/ci/tasks-s3/copy-artifacts.yml
  - put: pcfdev
    params:
      manifest: deploy-artifacts/manifest.yml
      path: deploy-artifacts/

- name: smoke-test
  plan:
  - get: my-repo
  - get: hello-artifacts
    trigger: true
    passed: [deploy]
  - task: smoke-test
    file: my-repo/ci/tasks-s3/smoke-test.yml
    params:
      test_url: ((TEST_URL))
